### PR TITLE
bugfixes

### PR DESCRIPTION
**Pull request by jdnrg**
Bug fixes to remove coding errors

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
@jdnrg Thanks for this. Can you sign the CLA so I can merge these in?

**Comment by jdnrg** [comment]
I am not going to be able to do that quickly. Feel free to redo the patch. It is trivial.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by 0xdabbad00** [comment]
Ok, just wanted to make sure I gave you credit if you wanted it.

**Comment by 0xdabbad00** [comment]
Resolved the issues via #456

**Pull request closed without merging**
