### PR TITLE
Implement Retries to deal with AWS request limits

### PR DESCRIPTION
**Pull request by Azulinho**
In my environment (which is fairly large) the collect phase fails every time with multiple `AWS request limits`.
This implements a simple retry decorator that performs exponential retries as required by the AWS API

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
Interesting.  I don't think I've run into any failures like this, and I've run this in very large environments.  boto should already be handing retries.   You can see their code at https://github.com/boto/botocore/blob/f8365c3a5b2074f3999c918a84e76869e58311c3/botocore/retryhandler.py

I wonder if any throttling you're experiencing is therefore more of a situation that botocore should be handling better.  Maybe check this file to see if it knows the service and exception are running into: https://github.com/boto/botocore/blob/9742777b370cf7e62f2bed8910765d912f21952a/botocore/data/_retry.json

**Comment by Azulinho** [comment]
I believe the `_retry.json` is only used by the functional tests,
https://github.com/boto/botocore/search?q=_retry.json&unscoped_q=_retry.json

99% of the errors I get are RequestLimitExceeded on the API, which is not handled by botocore, see:
https://github.com/boto/botocore/search?q=RequestLimitExceeded&type=Code

I think the only way today to have botocore retrying api calls, is with the `botocore.config.Config` block as such:
https://github.com/boto/botocore/issues/882#issuecomment-338846339

However that implementation above doesn't support exponential retries according to the PR for it
https://github.com/boto/botocore/pull/1260/files

AWS recommends that any AWSrequestlimit exceeded be retried on an exponential fallback https://docs.aws.amazon.com/general/latest/gr/api-retries.html, our environment is not just large in size (number of nodes and such) but has a large number of developer and services consuming the API endpoints, so for us, AWSrequestlimits are more the norm than an exception.

**Comment by copumpkin** [comment]
@Azulinho nah, `_retry.json` is used outside of tests, too: 

https://github.com/boto/botocore/blob/f7f811ef7b6a559e90b3852042a7e57beff4d926/botocore/client.py#L126-L128

https://github.com/boto/botocore/blob/f7f811ef7b6a559e90b3852042a7e57beff4d926/botocore/handlers.py#L299-L304

**Comment by 0xdabbad00** [comment]
From the link where @Azulinho states:
> AWS recommends that any AWSrequestlimit exceeded be retried on an exponential fallback https://docs.aws.amazon.com/general/latest/gr/api-retries.html,

The page at that URL states:
> Each AWS SDK implements automatic retry logic.

I have not seen RequestLimitExceeded in any environment I've run this in, so to avoid adding unnecessary code to this project, I'm going to close this PR.

**Pull request closed without merging**
