### PR TITLE
Enable to filter of regions based on whitelist/blacklist

### PR DESCRIPTION
**Pull request by syucream**
`collect` command calls many list/describe's and will consume quotas and many time. The whilelist/blacklist of regions will mitigate the issue.

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
The concept of only collecting data from specific regions was raised in https://github.com/duo-labs/cloudmapper/issues/304

I closed the issue then, and remain hesitant about this idea, as this will cause problems for some commands if us-east-1 is not collected from, and may cause unexpected results if someone has resources in a region that they do not collect from.

I don't believe CloudMapper will hit any quotas or rate limiting. Have you experienced that?

**Comment by syucream** [comment]
@0xdabbad00 We've actually exceeded rate limit on ECS. We have many ECS tasks and the collect command issues ecs-describe-tasks. I'm thinking it's a cause and it'll be mitigated 
 if https://github.com/duo-labs/cloudmapper/pull/413 works
On the other hands, our collect command execution spends about 23min so I hope to reduce the cost.

**Comment by ethanmdavidson** [comment]
I have run into another use case for this feature: something in our network security is blocking all requests to addresses outside the US, but instead of simply failing the connections will hang open until the connection times out. For every query to a region outside the US, we get the following:
```
 Making call for account-data/./mcwa/ap-south-1/ec2-describe-vpcs.json
Exception: Connection was closed before we received a valid response from endpoint URL: "https://ec2.ap-south-1.amazonaws.com/".
```
This causes the collect to take a long time because it spends a lot of time waiting on requests that are never going to respond. 

In other words, I think the feature still has value. I think you're correct that the default behavior should collect from all regions, but there still needs to be the option to restrict it if necessary, even if there are caveats like "us-east-1 is required".

PS: 
I tried the changes in the PR here, restricted it to just us-east-1 (where all my resources are) and the collect flew by in less than a minute. However, when trying to generate the report I got this exception:
```
* Getting resource counts
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/home/edavidson/cloudmapper/commands/report.py", line 461, in run
    report(accounts, config, args)
  File "/home/edavidson/cloudmapper/commands/report.py", line 97, in report
    account, args.stats_all_resources
  File "/home/edavidson/cloudmapper/shared/common.py", line 297, in get_account_stats
    query_aws(region.account, resource["source"], region),
  File "/home/edavidson/.local/share/virtualenvs/cloudmapper-pAfusy5u/lib/python3.6/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
```
I'm guessing it's trying to iterate over a region that wasn't collected. Don't have much time to dig into it right now.

**Comment by 0xdabbad00** [comment]
I should have merged this a long time ago. Another PR came up (#695) that does the same thing, except uses a single parameters `--regions`, so I'm going to merge that one.  I'm sorry for the horrible delays on my part. Thank you though.

**Comment by ozbillwang** [comment]
since we have `config.json`, could you set in it directly with nominated regions?

**Comment by 0xdabbad00** [comment]
Yes, if you want to provide a PR @ozbillwang I would get that merged in.

**Pull request closed without merging**
