### PR TITLE
Fixed permissions check

### PR DESCRIPTION
**Pull request by D00gs**

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
Thanks @D00gs. LGTM. This can be merged @steiza

**Comment by 0xdabbad00** [comment]
Thank you @D00gs! Can you sign the CLA so this can get merged?

**Comment by D00gs** [comment]
sorry missed the request. I have signed now

**Comment by w0rmr1d3r** [comment]
Let's merge this too!

**Comment by 0xdabbad00** [comment]
This PR looks wrong to me. We need the f strings so the variables get interpreted into the text.

**Pull request closed without merging**
