### PR TITLE
Remove Dockerfile

### PR DESCRIPTION
**Pull request by 0xdabbad00**

### CODE REVIEW

**Comment by mjallday** [comment]
why did this get removed?

**Comment by 0xdabbad00** [comment]
@mjallday I need to spend time to understand how this can be used effectively with Docker.  At this point in time, CloudMapper is a utility, like burp or vim, which don't run in docker containers normally, so I'm unsure if CloudMapper should for the way it works.  I've recognized that CloudMapper can be difficult to install, but I don't know if Docker is the correct solution for that.

**Comment by FernandoMiguel** [comment]
As someone who hates messy installs, and one of the first to make a Docker for this tool, I see huge value in it.
Think of it as app install... But all in a container, pun intended. 

Either that, or brew cask

**Comment by mjallday** [comment]
I tend to agree with having a docker container. You can package it another way but I really like docker since I don’t have to worry about biking my system purging and breaking everything (looking at you brew!)

My first instinct these days is to find a docker container for any project since it’s the same interface on any os.

**Pull request merged**
