### PR TITLE
Added missing required modules to requirements.txt

### PR DESCRIPTION
**Pull request by bmurtagh**
There are modules missing from the requirements.txt that needed to be manually installed via pip on my system when using the `stats` command. 

This PR adds them to the requirements.txt and the latest version that was installed.

### CODE REVIEW

**Comment by bmurtagh** [comment]
This PR includes a few additional modules than the PNG creation-specific ones in #704

**Comment by 0xdabbad00** [comment]
Thank you @bmurtagh. I'm guessing some of those such as `cycler` must be dependencies of the other packages, as I have not heard of them before.  I'll look into limiting the change to only the minimal packages needed.

**Comment by bmurtagh** [comment]
No problem @0xdabbad00, I hadn't heard of them either, but I was following the output from the execution and eventual errors. Basically turned into a `pip install` exercise for a few entries. Once those modules were installed we were good to go 👍 🚀

**Comment by 0xdabbad00** [comment]
Resolved these requirements issues via https://github.com/duo-labs/cloudmapper/pull/717/commits/195f03dfdad933f238ef52327118accb41a62ea8

I didn't want to merge in the extra unknown dependencies.

**Pull request closed without merging**
