### PR TITLE
Enable to filter ec2 instances by tags

### PR DESCRIPTION
**Pull request by syucream**
I want more flexible filters to display only important components, tag-based filter is one of the filter.

### CODE REVIEW

**Comment by syucream** [comment]
But it might be too flexible filter. What do you think?

**Comment by 0xdabbad00** [comment]
Thank you. This has some similarities with the PR #316 which is specific to the tag `Name` and additionally filters to ELB and RDS resources.  I think it makes sense to make this generalized as you have done.  I wonder if I should make it more generalized somehow to allow logic like `If Name=batch,Env=prod or Name=batch,Env=dev or Env=test`. I'm not sure how I could go about that though or how many use cases people might have around this, or if I should generalize this further beyond just tags but also be able to query based on things like the instance size.  I also sort of feel like I should have a way of high-lighting resources by tag.  Those ideas all would just result in me be over-whelmed though, so I think it makes sense to just use this as you've provided (additionally I'll extend it with the resources of PR #316) and it can be updated later if needed.

I'll do some testing and hopefully merge this soon.

**Comment by syucream** [comment]
The points you said are hard parts ... I think my conclusion is similar to yours; we should keep the filtering stuff simple now. This filter is easy to handle, just parsing options, applying them pyjq.

> if I should generalize this further beyond just tags but also be able to query based on things like the instance size.

I'm feeling it's good for the next step, but we need to know what kinds of / how many use cases there are.

> I'll do some testing and hopefully merge this soon.

oh I'll check it soon. 😅 🙏

**Comment by syucream** [comment]
@0xdabbad00 I added test code for the filter. It might help your checking. 🙏

**Comment by 0xdabbad00** [comment]
Thank you. I've started merging this locally with some additions so you'll be able to do:
```
--tags env=Prod --tags env=Test,name=bastion
```

Which will display any EC2 with the tag `env=Prod` OR any EC2 with both (env=Test AND name=bastion)

**Comment by 0xdabbad00** [comment]
I merged in your changes into PR #352.  I managed to get you in the logs for some of your commits, but not the later commit with the unit test, which I had to copy in manually. As you're aware this only filters the EC2s and not ELBs or RDSs.  I'm closing this PR as PR #352 absorbed the changes.

**Pull request closed without merging**
