### PR TITLE
Kbroughton

### PR DESCRIPTION
**Pull request by 0xdabbad00**
This corrects the issues in @kbroughton's PR #735

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
@steiza This can be merged

**Comment by steiza** [comment]
Oops! I think I created a merge conflict with this branch by landing https://github.com/duo-labs/cloudmapper/commit/ccd971c84c4cb0c6491ef6fe0faca097f68eb6ea. @0xdabbad00 do you want to resolve the merge conflict, or should I?

**Comment by 0xdabbad00** [comment]
@steiza I've resolved the conflict now.

**Comment by 0xdabbad00** [comment]
@kbroughton it is finally merged! I apologize this has taken me months.

**Pull request merged**
