### PR TITLE
Added feature to find unused ELBs

### PR DESCRIPTION
**Pull request by DanielRDias**
* Added feature to find unused elastic load balancers.

* Fixed test_find_unused
`test_find_unused_network_interfaces` had the name `test_find_unused_security_group`, because of this "real" `test_find_unused_security_group` was not running. After correcting the naming I noticed that  that `test_find_unused_security_group` was failing because it  requires `region.region` which was missing in `mock_region`.

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
Thank you @DanielRDias! Looks like the tests are failing now though, but based on your description it sounds like you had fixed it?

From the Travis CI, this is the error:
```
ERROR: test_find_unused_security_groups (test_find_unused.TestFindUnused)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/duo-labs/cloudmapper/tests/unit/test_find_unused.py", line 198, in test_find_unused_security_groups
    find_unused_security_groups(self.mock_region),
  File "/home/travis/build/duo-labs/cloudmapper/shared/find_unused.py", line 39, in find_unused_security_groups
    nodes = get_resource_nodes(region, outputfilter)
  File "/home/travis/build/duo-labs/cloudmapper/commands/prepare.py", line 353, in get_resource_nodes
    for ec2_json in get_ec2s(region):
  File "/home/travis/build/duo-labs/cloudmapper/commands/prepare.py", line 105, in get_ec2s
    return pyjq.all(resource_filter, instances)
  File "/home/travis/build/duo-labs/cloudmapper/.venv/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
```

**Comment by DanielRDias** [comment]
I was facing a similar issue when I corrected the test name.
```ERROR: test_find_unused_security_groups (tests.unit.test_find_unused.TestFindUnused)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniel/projects/cloudmapper/tests/unit/test_find_unused.py", line 198, in test_find_unused_security_groups
    find_unused_security_groups(self.mock_region),
  File "/home/daniel/projects/cloudmapper/shared/find_unused.py", line 39, in find_unused_security_groups
    nodes = get_resource_nodes(region, outputfilter)
  File "/home/daniel/projects/cloudmapper/commands/prepare.py", line 353, in get_resource_nodes
    for ec2_json in get_ec2s(region):
  File "/home/daniel/projects/cloudmapper/commands/prepare.py", line 103, in get_ec2s
    instances = query_aws(region.account, "ec2-describe-instances", region.region)
AttributeError: type object 'region' has no attribute 'region'
```

But after adding the region, all tests were executed successfully afterward.
I don't know what is failing on Travis since I can't reproduce the error on my machine.

All tests are passing for me:
```(cloudmapper) daniel@dias:~/projects/cloudmapper (git:feature/unused-elb)$ ./tests/scripts/unit_tests.sh ......................
Name                    Stmts   Miss  Cover
-------------------------------------------
commands/__init__.py        1      0   100%
commands/prepare.py       383    114    70%
shared/__init__.py          0      0   100%
shared/audit.py           421    138    67%
shared/common.py          201     71    65%
shared/find_unused.py      64     18    72%
shared/iam_audit.py       174     62    64%
shared/nodes.py           506     67    87%
shared/public.py          125     33    74%
shared/query.py            17      1    94%
-------------------------------------------
TOTAL                    1892    504    73%
----------------------------------------------------------------------
Ran 22 tests in 1.652s

OK

```

**Comment by 0xdabbad00** [comment]
Ok, I'm going to be traveling for the next week, but will look at this the week of September 9, and will be planning on putting out a big release then for https://github.com/duo-labs/cloudmapper/issues/483.

**Comment by 0xdabbad00** [comment]
I figured out the unit test issue. Thank you for uncovering that @DanielRDias !

**Pull request merged**
