### PR TITLE
Check that tags are not null before iterating over them

### PR DESCRIPTION
**Pull request by mulder-sean**

### CODE REVIEW

**Review by w0rmr1d3r — APPROVED** [review]

**Comment by 0xdabbad00** [comment]
@mulder-sean Can you remove the change to the .gitignore file?

**Comment by mulder-sean** [comment]
That was to prevent me from checking in my temp files from pycharm

**Comment by mulder-sean** [comment]
I removed it

**Comment by 0xdabbad00** [comment]
LGTM, this can be merged @steiza

**Pull request merged**
