### PR TITLE
Fix issues #823 , #620 and #834

### PR DESCRIPTION
**Pull request by roskyfrosky**
Fix Issue 834

### CODE REVIEW

**Comment by w0rmr1d3r** [comment]
@roskyfrosky this actually resolves issue #620 as well, but I made a separate PR for it https://github.com/duo-labs/cloudmapper/pull/849

**Comment by roskyfrosky** [comment]
ok @w0rmr1d3r! I have added Turbot vendor too named in #823

**Comment by w0rmr1d3r** [comment]
Awesome @roskyfrosky ! 
Then, this PR actually solves issues #823 , #620 and #834 !
Can you put that in the description? Thank you!

**Comment by roskyfrosky** [comment]
@w0rmr1d3r Done.

**Comment by roskyfrosky** [comment]
@w0rmr1d3r Added some checks for collect and stats command. Added the posibility to choose the output filename for report command too.

**Comment by w0rmr1d3r** [comment]
Alright @roskyfrosky !
I've been monitoring the PR lately. It actually does more than one thing and more than what the title and description say.
I can see that it's getting updated from your `main` branch.
It'd be better if it got split into different PRs, and every PR only fixed/solved one thing instead.
That's only my opinion, I don't know how the owners of the repo want it. But for me, it'd be easier to review and to merge.

**Comment by roskyfrosky** [comment]
@w0rmr1d3r  ok! I close this PR and open a new one for each of the changes.

**Pull request closed without merging**
