### PR TITLE
Remove unneeded extra policy 

### PR DESCRIPTION
**Pull request by 0xdabbad00**
The SecurityAudit policy now has everything. See https://github.com/SummitRoute/aws_managed_policies/commit/df4502d37e7126d9e5fe8add38cd9ab8aed8f3eb#diff-831d569bb19b182bb12f48b976d5c98fR59

### CODE REVIEW

**Comment by stepkirk** [comment]
After removing the extra policy and running a data collection, I received the following three types of errors:

ClientError: An error occurred (AccessDeniedException) when calling the GetLoadBalancers operation: User: <ARN> is not authorized to perform: lightsail:GetLoadBalancers on resource: <ARN>

ClientError: An error occurred (AccessDeniedException) when calling the GetDeployments operation: User: <ARN> is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-west-2::/restapis/<removed>/deployments

ClientError: An error occurred (AccessDeniedException) when calling the GetStages operation: User: <ARN> is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:ap-south-1::/restapis/<removed>/stages

Added the following inline policy to get the errors to cease:

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "lightsail:GetLoadBalancers"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Effect": "Allow",
            "Action": [
                "apigateway:GET"
            ],
            "Resource": [
                "arn:aws:apigateway:*::/restapis/*/deployments",
                "arn:aws:apigateway:*::/restapis/*/stages"
            ]
        }
    ]
}

**Comment by 0xdabbad00** [comment]
@stepkirk I'm not sure on what to do for the lightsail privileges.  I used to have `lightsail:GetLoadBalancers` but it was showing up as an error for people in the web console as an unknown privilege to AWS (https://github.com/duo-labs/cloudmapper/commit/6e2f4f128d58704e8f937deab8bcda1a4afe60a3#diff-04c6e90faac2675aa89e2176d2eec7d8L134).  See the issue https://github.com/duo-labs/cloudmapper/issues/212

So I removed that privilege and hadn't heard anything. I've run CloudMapper in environments, and didn't get any errors about it, so maybe it only errors when you actually have load balancers?  It's been my understanding that the privilege `lightsail:GetInstances` somehow maps to both the API calls `lightsail:GetInstances` and `lightsail:GetLoadBalancers` behind the scenes, but maybe that is not true?

As for the API Gateway stuff, I'm probably going to remove the collection of those items.  They aren't used except by the `api_endpoints` command, which I don't think get's much attention.

**Comment by 0xdabbad00** [comment]
@stepkirk Also, thanks for reporting this.  A lot of issues people have never get reported, so thank you.

**Comment by stepkirk** [comment]
> @stepkirk I'm not sure on what to do for the lightsail privileges. I used to have `lightsail:GetLoadBalancers` but it was showing up as an error for people in the web console as an unknown privilege to AWS ([6e2f4f1#diff-04c6e90faac2675aa89e2176d2eec7d8L134](https://github.com/duo-labs/cloudmapper/commit/6e2f4f128d58704e8f937deab8bcda1a4afe60a3#diff-04c6e90faac2675aa89e2176d2eec7d8L134)). See the issue #212

Ah, I remember this. I wonder if AWS fixed something recently where this is no longer an issue. No more errors for me after adding it (and no yellow exclamation points in the UI so...)

> So I removed that privilege and hadn't heard anything. I've run CloudMapper in environments, and didn't get any errors about it, so maybe it only errors when you actually have load balancers?

That could be. We don't use Lightsail much and certainly not in every region that the error pops up in so not sure.

> It's been my understanding that the privilege `lightsail:GetInstances` somehow maps to both the API calls `lightsail:GetInstances` and `lightsail:GetLoadBalancers` behind the scenes, but maybe that is not true?

Doesn't seem to be true from my testing. `lightsail:GetInstances` is in the **SecurityAudit** policy but the error occurred until I added `lightsail:GetLoadBalancers` into the inline policy shown above.

> As for the API Gateway stuff, I'm probably going to remove the collection of those items. They aren't used except by the `api_endpoints` command, which I don't think get's much attention.

Good call, I think. I haven't found a compelling use-case for the `api_endpoints` output.

Appreciate you putting so much time into this tool. I find it very useful.

**Pull request merged**
